{% set name = "napari-caphid" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-caphid-{{ version }}.tar.gz
  sha256: fd78f3d19ee48bea91713a8c95c9953b1290159a28df99168e58a923e7f54f18

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:    
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - opencv
    - pandas
    - pillow
    - python >={{ python_min }},<3.11
    - qtpy
    - scikit-image
    - tqdm

test:
  imports:
    - napari_caphid
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-caphid
  summary: Annotation of aphid and update table
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/hereariim/napari-caphid

extra:
  recipe-maintainers:
    - goanpeca
    - hereariim
    - jaimergp
